### ISSUE TITLE
Release as Python package in PyPI

### ISSUE THREAD

**Issue by jaraco** [JackToaster/Reassuring-Parable-Generator#1]
I'd like to use this generator in other tools (for which I'll file a separate ticket). Would you be open to a pull request that takes the code and packages it up for release in PyPI? Would you like to own the release process to PyPI, rely on someone else like myself to do it, or maybe some shared process?

**Comment by JackToaster** [comment]
I'm not too interested in putting much more work into this project. This was just a weekend project for me, and I never expected it to gain so much attention. However, if you would like to do any work on it, feel free to do so. If I get sufficiently bored in the future, I might work more on this, too.
