### ISSUE TITLE
Add support for pmxbot

### ISSUE THREAD

**Issue by jaraco** [JackToaster/Reassuring-Parable-Generator#2]
This functionality would be a great addition to a [pmxbot](https://pypi.org/project/pmxbot). Adding support would be straightforward once #1 is complete. Then someone running pmxbot on IRC or [Slack](https://slack.com) could do something like:

```
user: !reassure
pmxbot: A computer will never have the ability to enjoy a song.
```

Also consider the plugin might also take a nickname and substitute for "a computer" and "computers":

```
user: !reassure otheruser
pmxbot: otheruser will never enjoy a poem.
```

**Comment by JackToaster** [comment]
I'm not too interested in putting much more work into this project. This was just a weekend project for me, and I never expected it to gain so much attention. However, if you would like to do any work on it, feel free to do so. If I get sufficiently bored in the future, I might work more on this, too.
